import { evidencePoints } from "./marketing-data";
import { IconShield } from "./marketing-icons";
import {
  MarketingPageSection,
  MarketingSectionIntro,
} from "./marketing-section";

export function MarketingEvidence() {
  return (
    <MarketingPageSection ariaLabelledBy="evidence-heading">
      <div className="rounded-2xl border border-forge-gold/25 bg-gradient-to-br from-forge-gold/5 to-forge-surface-raised p-6 sm:p-8 md:p-10">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:gap-10">
          <div className="shrink-0">
            <div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-forge-gold/30 bg-forge-gold/10 text-forge-gold">
              <IconShield className="h-7 w-7" />
            </div>
          </div>
          <div className="min-w-0 flex-1">
            <MarketingSectionIntro
              headingId="evidence-heading"
              eyebrow="Built on evidence"
              eyebrowClassName="text-forge-gold"
              title="Your plan, backed by research — not hype"
              description="Program logic draws from peer-reviewed sports science: protein targets, deficit rates, hypertrophy volume, and recovery timing. The rules are deterministic and citable — workout structure is never generated by an LLM."
            />

            <ul className="mt-6 space-y-3 sm:mt-8 sm:space-y-4">
              {evidencePoints.map((point) => (
                <li
                  key={point}
                  className="flex gap-3 text-sm leading-relaxed text-forge-text sm:gap-4 sm:text-base"
                >
                  <span
                    className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-forge-gold"
                    aria-hidden
                  />
                  {point}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </MarketingPageSection>
  );
}
