import { evidencePoints } from "./marketing-data";
import { MarketingSection, MarketingSectionIntro } from "./marketing-section";

export function MarketingEvidence() {
  return (
    <MarketingSection variant="highlight">
      <MarketingSectionIntro
        eyebrow="Built on evidence"
        eyebrowClassName="text-forge-gold"
        title="Your plan, backed by research — not hype"
        description="Program logic draws from peer-reviewed sports science: protein targets, deficit rates, hypertrophy volume, and recovery timing. The rules are deterministic and citable — workout structure is never generated by an LLM."
      />

      <ul className="mt-6 space-y-3 sm:mt-8 sm:space-y-4">
        {evidencePoints.map((point) => (
          <li
            key={point}
            className="flex gap-3 text-sm leading-relaxed text-forge-text sm:gap-4 sm:text-base"
          >
            <span
              className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-forge-gold"
              aria-hidden
            />
            {point}
          </li>
        ))}
      </ul>
    </MarketingSection>
  );
}
