import { EvidenceBrowser } from "@/components/evidence/evidence-browser";
import { appHeaderGap, appPagePadding } from "@/components/layout/page-layout";
import { getRules } from "@forgefit/evidence-kb";
import { getEvidencePageData } from "@/lib/evidence/service";
import { createClient } from "@/lib/supabase/server";

interface EvidencePageProps {
  searchParams: Promise<{
    focus?: string;
    related?: string;
  }>;
}

export default async function EvidencePage({ searchParams }: EvidencePageProps) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const params = await searchParams;
  const focusRuleId = params.focus;
  const relatedRuleIds = params.related
    ? params.related.split(",").filter(Boolean)
    : [];

  const data = user
    ? await getEvidencePageData(user.id)
    : {
        knowledgeBaseVersion: "0.2.0",
        hasProgram: false,
        appliedRuleIds: [],
        appliedRules: [],
        matchedRules: [],
        allRules: getRules(),
      };

  return (
    <div className={appPagePadding}>
      <p className="font-display text-sm font-semibold uppercase tracking-widest text-forge-gold">
        Transparency
      </p>
      <h1 className="font-display mt-1 text-3xl font-bold text-forge-text">
        Evidence behind your plan
      </h1>
      <p className="mt-3 max-w-2xl text-sm leading-relaxed text-forge-muted">
        forgeFit never guesses your programming in a chatbot. Every target and
        training decision traces to a versioned rule in our evidence knowledge
        base — each with cited sources you can read for yourself.
      </p>

      <div className={`${appHeaderGap} space-y-4`}>
        <section className="rounded-2xl border border-[var(--border)] bg-forge-surface-raised p-4 sm:p-5">
          <div className="grid gap-3 sm:grid-cols-3">
            <Stat
              label="Rules in your plan"
              value={String(data.appliedRuleIds.length)}
            />
            <Stat
              label="Knowledge base version"
              value={data.knowledgeBaseVersion}
            />
            <Stat
              label="Total rules available"
              value={String(data.allRules.length)}
            />
          </div>
          {!data.hasProgram && (
            <p className="mt-4 text-sm text-forge-muted">
              Complete onboarding and generate a program to see which rules are
              active for you. You can still browse the full library below.
            </p>
          )}
        </section>

        <EvidenceBrowser
          appliedRuleIds={data.appliedRuleIds}
          allRules={data.allRules}
          focusRuleId={focusRuleId}
          relatedRuleIds={relatedRuleIds}
        />
        {!user && (
          <p className="text-sm text-forge-muted">
            Sign in to highlight which rules are active in your personalized plan.
          </p>
        )}

        <section className="rounded-2xl border border-[var(--border)] bg-forge-surface px-4 py-4 text-sm text-forge-muted sm:px-5">
          <p className="font-medium text-forge-text">How we use this</p>
          <ul className="mt-3 space-y-2">
            <li>
              Rules are matched to your goal, experience, body metrics, and
              recovery tools — not generated by AI.
            </li>
            <li>
              Nutrition targets, training volume, recovery blocks, and
              projections each reference specific rule IDs for traceability.
            </li>
            <li>
              Confidence labels reflect how strong and consistent the underlying
              research is — not marketing claims.
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-[var(--border)] bg-forge-surface px-3 py-3">
      <p className="text-xs text-forge-muted">{label}</p>
      <p className="mt-1 font-display text-lg font-bold text-forge-text">
        {value}
      </p>
    </div>
  );
}
