import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  {
    id: "barbell_squat",
    name: "Barbell Back Squat",
    movementPattern: "squat",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["barbell", "squat_rack"],
    difficulty: "intermediate",
    priority: 10,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    movementPattern: "squat",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["dumbbells", "kettlebells"],
    difficulty: "beginner",
    priority: 8,
  },
  {
    id: "leg_press",
    name: "Leg Press",
    movementPattern: "squat",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["machines"],
    difficulty: "beginner",
    priority: 7,
  },
  {
    id: "bodyweight_squat",
    name: "Bodyweight Squat",
    movementPattern: "squat",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["bodyweight_only"],
    difficulty: "beginner",
    priority: 6,
  },
  {
    id: "barbell_deadlift",
    name: "Barbell Deadlift",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "back"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    priority: 10,
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    priority: 9,
  },
  {
    id: "hip_hinge_machine",
    name: "Back Extension",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "back"],
    equipment: ["machines", "bodyweight_only"],
    difficulty: "beginner",
    priority: 5,
  },
  {
    id: "barbell_bench",
    name: "Barbell Bench Press",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps"],
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
    priority: 10,
  },
  {
    id: "dumbbell_bench",
    name: "Dumbbell Bench Press",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    priority: 9,
  },
  {
    id: "push_up",
    name: "Push-up",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps"],
    equipment: ["bodyweight_only"],
    difficulty: "beginner",
    priority: 7,
  },
  {
    id: "cable_fly",
    name: "Cable Chest Fly",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    equipment: ["cables"],
    difficulty: "beginner",
    priority: 5,
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    priority: 9,
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    equipment: ["machines"],
    difficulty: "beginner",
    priority: 7,
  },
  {
    id: "barbell_row",
    name: "Barbell Row",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back", "biceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    priority: 9,
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell Row",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back", "biceps"],
    equipment: ["dumbbells", "bench"],
    difficulty: "beginner",
    priority: 8,
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back", "biceps"],
    equipment: ["cables", "machines"],
    difficulty: "beginner",
    priority: 7,
  },
  {
    id: "pull_up",
    name: "Pull-up",
    movementPattern: "vertical_pull",
    primaryMuscles: ["back", "biceps"],
    equipment: ["pull_up_bar"],
    difficulty: "intermediate",
    priority: 9,
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    movementPattern: "vertical_pull",
    primaryMuscles: ["back", "biceps"],
    equipment: ["cables", "machines"],
    difficulty: "beginner",
    priority: 8,
  },
  {
    id: "band_pulldown",
    name: "Band Pulldown",
    movementPattern: "vertical_pull",
    primaryMuscles: ["back"],
    equipment: ["resistance_bands"],
    difficulty: "beginner",
    priority: 6,
  },
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    movementPattern: "lunge",
    primaryMuscles: ["quadriceps", "glutes"],
    equipment: ["dumbbells", "bodyweight_only"],
    difficulty: "beginner",
    priority: 6,
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    movementPattern: "isolation_legs",
    primaryMuscles: ["hamstrings"],
    equipment: ["machines"],
    difficulty: "beginner",
    priority: 5,
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    movementPattern: "isolation_legs",
    primaryMuscles: ["quadriceps"],
    equipment: ["machines"],
    difficulty: "beginner",
    priority: 5,
  },
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    movementPattern: "isolation_arms",
    primaryMuscles: ["biceps"],
    equipment: ["barbell", "dumbbells"],
    difficulty: "beginner",
    priority: 4,
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdown",
    movementPattern: "isolation_arms",
    primaryMuscles: ["triceps"],
    equipment: ["cables"],
    difficulty: "beginner",
    priority: 4,
  },
  {
    id: "plank",
    name: "Plank",
    movementPattern: "core",
    primaryMuscles: ["core"],
    equipment: ["bodyweight_only"],
    difficulty: "beginner",
    priority: 5,
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    movementPattern: "core",
    primaryMuscles: ["core"],
    equipment: ["cables"],
    difficulty: "beginner",
    priority: 4,
  },
  {
    id: "treadmill_incline_walk",
    name: "Incline Walk",
    movementPattern: "cardio",
    primaryMuscles: ["cardio"],
    equipment: ["cardio_machines"],
    difficulty: "beginner",
    priority: 3,
  },
  {
    id: "bike_intervals",
    name: "Bike Intervals",
    movementPattern: "cardio",
    primaryMuscles: ["cardio"],
    equipment: ["cardio_machines"],
    difficulty: "beginner",
    priority: 3,
  },
];
