/** Curated US chain items — macros are approximate from published nutrition pages. */

export interface RestaurantChain {
  id: string;
  name: string;
  nutritionUrl: string;
}

export interface RestaurantMenuItem {
  id: string;
  chainId: string;
  name: string;
  servingDescription: string;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
}

export const RESTAURANT_CHAINS: readonly RestaurantChain[] = [
  {
    id: "chipotle",
    name: "Chipotle",
    nutritionUrl: "https://www.chipotle.com/nutrition-calculator",
  },
  {
    id: "mcdonalds",
    name: "McDonald's",
    nutritionUrl: "https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html",
  },
  {
    id: "subway",
    name: "Subway",
    nutritionUrl: "https://www.subway.com/en-us/menunutrition/nutrition",
  },
  {
    id: "chickfila",
    name: "Chick-fil-A",
    nutritionUrl: "https://www.chick-fil-a.com/nutrition-allergens",
  },
  {
    id: "wendys",
    name: "Wendy's",
    nutritionUrl: "https://www.wendys.com/nutrition",
  },
  {
    id: "tacobell",
    name: "Taco Bell",
    nutritionUrl: "https://www.tacobell.com/nutrition/info",
  },
  {
    id: "starbucks",
    name: "Starbucks",
    nutritionUrl: "https://www.starbucks.com/menu/nutrition-info",
  },
  {
    id: "panera",
    name: "Panera",
    nutritionUrl: "https://www.panerabread.com/en-us/menu/nutrition.html",
  },
  {
    id: "sweetgreen",
    name: "Sweetgreen",
    nutritionUrl: "https://www.sweetgreen.com/menu",
  },
  {
    id: "cava",
    name: "Cava",
    nutritionUrl: "https://cava.com/menu",
  },
  {
    id: "shakeshack",
    name: "Shake Shack",
    nutritionUrl: "https://www.shakeshack.com/nutrition",
  },
  {
    id: "panda",
    name: "Panda Express",
    nutritionUrl: "https://www.pandaexpress.com/nutrition",
  },
  {
    id: "popeyes",
    name: "Popeyes",
    nutritionUrl: "https://www.popeyes.com/nutrition",
  },
  {
    id: "fiveguys",
    name: "Five Guys",
    nutritionUrl: "https://www.fiveguys.com/menu/nutrition-info",
  },
  {
    id: "in-n-out",
    name: "In-N-Out",
    nutritionUrl: "https://www.in-n-out.com/menu",
  },
  {
    id: "culvers",
    name: "Culver's",
    nutritionUrl: "https://www.culvers.com/menu-and-nutrition",
  },
] as const;

export const RESTAURANT_MENU_ITEMS: readonly RestaurantMenuItem[] = [
  // Chipotle
  {
    id: "chipotle-chicken-bowl",
    chainId: "chipotle",
    name: "Chicken bowl (typical)",
    servingDescription: "1 bowl · rice, chicken, beans, salsa",
    calories: 665,
    proteinG: 42,
    carbsG: 65,
    fatG: 22,
  },
  {
    id: "chipotle-steak-burrito",
    chainId: "chipotle",
    name: "Steak burrito",
    servingDescription: "1 burrito · full toppings",
    calories: 820,
    proteinG: 48,
    carbsG: 78,
    fatG: 32,
  },
  {
    id: "chipotle-chicken-burrito",
    chainId: "chipotle",
    name: "Chicken burrito",
    servingDescription: "1 burrito · rice, chicken, beans",
    calories: 750,
    proteinG: 46,
    carbsG: 72,
    fatG: 28,
  },
  {
    id: "chipotle-steak-bowl",
    chainId: "chipotle",
    name: "Steak bowl",
    servingDescription: "1 bowl · rice, steak, fajita veggies",
    calories: 690,
    proteinG: 44,
    carbsG: 62,
    fatG: 26,
  },
  {
    id: "chipotle-chicken-salad",
    chainId: "chipotle",
    name: "Chicken salad",
    servingDescription: "1 salad · lettuce, chicken, salsa",
    calories: 420,
    proteinG: 38,
    carbsG: 18,
    fatG: 20,
  },
  {
    id: "chipotle-carnitas-bowl",
    chainId: "chipotle",
    name: "Carnitas bowl",
    servingDescription: "1 bowl · rice, carnitas, beans",
    calories: 720,
    proteinG: 40,
    carbsG: 68,
    fatG: 30,
  },
  {
    id: "chipotle-sofritas-bowl",
    chainId: "chipotle",
    name: "Sofritas bowl",
    servingDescription: "1 bowl · rice, sofritas, veggies",
    calories: 580,
    proteinG: 22,
    carbsG: 70,
    fatG: 24,
  },
  {
    id: "chipotle-chips-guac",
    chainId: "chipotle",
    name: "Chips & guacamole",
    servingDescription: "1 order",
    calories: 770,
    proteinG: 9,
    carbsG: 74,
    fatG: 50,
  },
  // McDonald's
  {
    id: "mcdonalds-big-mac",
    chainId: "mcdonalds",
    name: "Big Mac",
    servingDescription: "1 sandwich",
    calories: 590,
    proteinG: 26,
    carbsG: 46,
    fatG: 34,
  },
  {
    id: "mcdonalds-10-nuggets",
    chainId: "mcdonalds",
    name: "10 pc Chicken McNuggets",
    servingDescription: "10 pieces",
    calories: 410,
    proteinG: 23,
    carbsG: 26,
    fatG: 24,
  },
  {
    id: "mcdonalds-quarter-pounder",
    chainId: "mcdonalds",
    name: "Quarter Pounder w/ Cheese",
    servingDescription: "1 sandwich",
    calories: 520,
    proteinG: 30,
    carbsG: 42,
    fatG: 26,
  },
  {
    id: "mcdonalds-mcchicken",
    chainId: "mcdonalds",
    name: "McChicken",
    servingDescription: "1 sandwich",
    calories: 400,
    proteinG: 14,
    carbsG: 39,
    fatG: 21,
  },
  {
    id: "mcdonalds-filet-o-fish",
    chainId: "mcdonalds",
    name: "Filet-O-Fish",
    servingDescription: "1 sandwich",
    calories: 390,
    proteinG: 16,
    carbsG: 39,
    fatG: 19,
  },
  {
    id: "mcdonalds-egg-mcmuffin",
    chainId: "mcdonalds",
    name: "Egg McMuffin",
    servingDescription: "1 sandwich",
    calories: 310,
    proteinG: 17,
    carbsG: 30,
    fatG: 13,
  },
  {
    id: "mcdonalds-sausage-burrito",
    chainId: "mcdonalds",
    name: "Sausage Burrito",
    servingDescription: "1 burrito",
    calories: 310,
    proteinG: 13,
    carbsG: 26,
    fatG: 17,
  },
  {
    id: "mcdonalds-medium-fries",
    chainId: "mcdonalds",
    name: "Medium French Fries",
    servingDescription: "1 medium order",
    calories: 320,
    proteinG: 4,
    carbsG: 43,
    fatG: 15,
  },
  {
    id: "mcdonalds-6-nuggets-meal",
    chainId: "mcdonalds",
    name: "6 pc McNuggets",
    servingDescription: "6 pieces",
    calories: 250,
    proteinG: 14,
    carbsG: 15,
    fatG: 15,
  },
  // Subway
  {
    id: "subway-6-turkey",
    chainId: "subway",
    name: "6\" Turkey Breast",
    servingDescription: "6 inch · wheat, veggies",
    calories: 280,
    proteinG: 18,
    carbsG: 40,
    fatG: 4,
  },
  {
    id: "subway-6-chicken",
    chainId: "subway",
    name: "6\" Grilled Chicken",
    servingDescription: "6 inch · wheat, veggies",
    calories: 320,
    proteinG: 26,
    carbsG: 40,
    fatG: 5,
  },
  {
    id: "subway-6-rotisserie",
    chainId: "subway",
    name: "6\" Rotisserie Chicken",
    servingDescription: "6 inch · wheat, veggies",
    calories: 350,
    proteinG: 29,
    carbsG: 40,
    fatG: 8,
  },
  {
    id: "subway-6-tuna",
    chainId: "subway",
    name: "6\" Tuna",
    servingDescription: "6 inch · wheat, veggies",
    calories: 480,
    proteinG: 20,
    carbsG: 40,
    fatG: 25,
  },
  {
    id: "subway-6-steak-cheese",
    chainId: "subway",
    name: "6\" Steak & Cheese",
    servingDescription: "6 inch · wheat, veggies",
    calories: 380,
    proteinG: 24,
    carbsG: 42,
    fatG: 12,
  },
  {
    id: "subway-6-veggie",
    chainId: "subway",
    name: "6\" Veggie Delite",
    servingDescription: "6 inch · wheat, veggies",
    calories: 230,
    proteinG: 9,
    carbsG: 42,
    fatG: 3,
  },
  {
    id: "subway-12-chicken",
    chainId: "subway",
    name: "12\" Grilled Chicken",
    servingDescription: "12 inch · wheat, veggies",
    calories: 640,
    proteinG: 52,
    carbsG: 80,
    fatG: 10,
  },
  {
    id: "subway-protein-bowl",
    chainId: "subway",
    name: "Protein Bowl · Chicken",
    servingDescription: "1 bowl · no bread",
    calories: 370,
    proteinG: 35,
    carbsG: 16,
    fatG: 18,
  },
  // Chick-fil-A
  {
    id: "chickfila-sandwich",
    chainId: "chickfila",
    name: "Chick-fil-A Sandwich",
    servingDescription: "1 sandwich",
    calories: 440,
    proteinG: 28,
    carbsG: 40,
    fatG: 19,
  },
  {
    id: "chickfila-spicy-sandwich",
    chainId: "chickfila",
    name: "Spicy Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 450,
    proteinG: 28,
    carbsG: 42,
    fatG: 19,
  },
  {
    id: "chickfila-grilled-sandwich",
    chainId: "chickfila",
    name: "Grilled Chicken Sandwich",
    servingDescription: "1 sandwich · multigrain bun",
    calories: 390,
    proteinG: 28,
    carbsG: 44,
    fatG: 12,
  },
  {
    id: "chickfila-nuggets-8",
    chainId: "chickfila",
    name: "8 ct Nuggets",
    servingDescription: "8 pieces · breaded",
    calories: 250,
    proteinG: 27,
    carbsG: 11,
    fatG: 11,
  },
  {
    id: "chickfila-nuggets-12",
    chainId: "chickfila",
    name: "12 ct Nuggets",
    servingDescription: "12 pieces · breaded",
    calories: 380,
    proteinG: 40,
    carbsG: 16,
    fatG: 17,
  },
  {
    id: "chickfila-grilled-nuggets-8",
    chainId: "chickfila",
    name: "8 ct Grilled Nuggets",
    servingDescription: "8 pieces · grilled",
    calories: 130,
    proteinG: 25,
    carbsG: 1,
    fatG: 3,
  },
  {
    id: "chickfila-strips-4",
    chainId: "chickfila",
    name: "4 ct Chick-n-Strips",
    servingDescription: "4 strips",
    calories: 440,
    proteinG: 39,
    carbsG: 22,
    fatG: 22,
  },
  {
    id: "chickfila-cool-wrap",
    chainId: "chickfila",
    name: "Grilled Chicken Cool Wrap",
    servingDescription: "1 wrap",
    calories: 350,
    proteinG: 42,
    carbsG: 29,
    fatG: 14,
  },
  {
    id: "chickfila-market-salad",
    chainId: "chickfila",
    name: "Market Salad w/ Grilled Chicken",
    servingDescription: "1 salad · with toppings",
    calories: 320,
    proteinG: 28,
    carbsG: 20,
    fatG: 14,
  },
  {
    id: "chickfila-spicy-southwest-salad",
    chainId: "chickfila",
    name: "Spicy Southwest Salad w/ Grilled Chicken",
    servingDescription: "1 salad · with dressing",
    calories: 680,
    proteinG: 42,
    carbsG: 38,
    fatG: 40,
  },
  {
    id: "chickfila-egg-white-grill",
    chainId: "chickfila",
    name: "Egg White Grill",
    servingDescription: "1 sandwich",
    calories: 300,
    proteinG: 26,
    carbsG: 29,
    fatG: 8,
  },
  {
    id: "chickfila-chicken-biscuit",
    chainId: "chickfila",
    name: "Chicken Biscuit",
    servingDescription: "1 biscuit sandwich",
    calories: 460,
    proteinG: 19,
    carbsG: 45,
    fatG: 23,
  },
  {
    id: "chickfila-hash-scramble",
    chainId: "chickfila",
    name: "Hash Brown Scramble Bowl w/ Sausage",
    servingDescription: "1 bowl",
    calories: 720,
    proteinG: 28,
    carbsG: 38,
    fatG: 52,
  },
  {
    id: "chickfila-waffle-fries-med",
    chainId: "chickfila",
    name: "Medium Waffle Fries",
    servingDescription: "1 medium order",
    calories: 420,
    proteinG: 5,
    carbsG: 45,
    fatG: 24,
  },
  {
    id: "chickfila-yogurt-parfait",
    chainId: "chickfila",
    name: "Greek Yogurt Parfait",
    servingDescription: "1 cup · granola & berries",
    calories: 270,
    proteinG: 13,
    carbsG: 36,
    fatG: 9,
  },
  // Wendy's
  {
    id: "wendys-daves-single",
    chainId: "wendys",
    name: "Dave's Single",
    servingDescription: "1 burger",
    calories: 590,
    proteinG: 29,
    carbsG: 39,
    fatG: 34,
  },
  {
    id: "wendys-daves-double",
    chainId: "wendys",
    name: "Dave's Double",
    servingDescription: "1 burger",
    calories: 850,
    proteinG: 47,
    carbsG: 40,
    fatG: 54,
  },
  {
    id: "wendys-spicy-chicken",
    chainId: "wendys",
    name: "Spicy Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 510,
    proteinG: 28,
    carbsG: 48,
    fatG: 22,
  },
  {
    id: "wendys-grilled-chicken",
    chainId: "wendys",
    name: "Grilled Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 370,
    proteinG: 34,
    carbsG: 36,
    fatG: 10,
  },
  {
    id: "wendys-10-nuggets",
    chainId: "wendys",
    name: "10 pc Chicken Nuggets",
    servingDescription: "10 pieces",
    calories: 450,
    proteinG: 22,
    carbsG: 28,
    fatG: 28,
  },
  {
    id: "wendys-apple-pecan-salad",
    chainId: "wendys",
    name: "Apple Pecan Salad w/ Grilled Chicken",
    servingDescription: "1 full salad",
    calories: 560,
    proteinG: 38,
    carbsG: 42,
    fatG: 26,
  },
  {
    id: "wendys-chili-large",
    chainId: "wendys",
    name: "Large Chili",
    servingDescription: "1 large cup",
    calories: 340,
    proteinG: 24,
    carbsG: 28,
    fatG: 14,
  },
  {
    id: "wendys-baked-potato",
    chainId: "wendys",
    name: "Baked Potato w/ Cheese & Bacon",
    servingDescription: "1 potato",
    calories: 480,
    proteinG: 14,
    carbsG: 52,
    fatG: 24,
  },
  // Taco Bell
  {
    id: "tacobell-crunchwrap",
    chainId: "tacobell",
    name: "Beef Crunchwrap Supreme",
    servingDescription: "1 wrap",
    calories: 530,
    proteinG: 16,
    carbsG: 47,
    fatG: 30,
  },
  {
    id: "tacobell-burrito-supreme",
    chainId: "tacobell",
    name: "Burrito Supreme · Beef",
    servingDescription: "1 burrito",
    calories: 390,
    proteinG: 16,
    carbsG: 45,
    fatG: 16,
  },
  {
    id: "tacobell-chicken-qesadilla",
    chainId: "tacobell",
    name: "Chicken Quesadilla",
    servingDescription: "1 quesadilla",
    calories: 510,
    proteinG: 27,
    carbsG: 37,
    fatG: 28,
  },
  {
    id: "tacobell-crunchy-taco",
    chainId: "tacobell",
    name: "Crunchy Taco · Beef",
    servingDescription: "1 taco",
    calories: 170,
    proteinG: 8,
    carbsG: 13,
    fatG: 10,
  },
  {
    id: "tacobell-soft-taco",
    chainId: "tacobell",
    name: "Soft Taco · Chicken",
    servingDescription: "1 taco",
    calories: 180,
    proteinG: 12,
    carbsG: 16,
    fatG: 7,
  },
  {
    id: "tacobell-power-bowl",
    chainId: "tacobell",
    name: "Power Menu Bowl · Chicken",
    servingDescription: "1 bowl · no shell",
    calories: 470,
    proteinG: 26,
    carbsG: 42,
    fatG: 20,
  },
  {
    id: "tacobell-beans-rice",
    chainId: "tacobell",
    name: "Black Beans & Rice",
    servingDescription: "1 side",
    calories: 190,
    proteinG: 6,
    carbsG: 32,
    fatG: 4,
  },
  {
    id: "tacobell-cheesy-gordita",
    chainId: "tacobell",
    name: "Cheesy Gordita Crunch",
    servingDescription: "1 item",
    calories: 500,
    proteinG: 20,
    carbsG: 42,
    fatG: 28,
  },
  // Starbucks
  {
    id: "starbucks-egg-bites",
    chainId: "starbucks",
    name: "Egg White & Roasted Red Pepper Bites",
    servingDescription: "2 bites",
    calories: 170,
    proteinG: 13,
    carbsG: 11,
    fatG: 8,
  },
  {
    id: "starbucks-protein-box",
    chainId: "starbucks",
    name: "Protein Box",
    servingDescription: "1 box · eggs, cheese, fruit, peanut butter",
    calories: 470,
    proteinG: 23,
    carbsG: 39,
    fatG: 24,
  },
  {
    id: "starbucks-bacon-gouda",
    chainId: "starbucks",
    name: "Bacon, Gouda & Egg Sandwich",
    servingDescription: "1 sandwich",
    calories: 360,
    proteinG: 18,
    carbsG: 34,
    fatG: 17,
  },
  {
    id: "starbucks-turkey-bacon",
    chainId: "starbucks",
    name: "Reduced-Fat Turkey Bacon Sandwich",
    servingDescription: "1 sandwich",
    calories: 230,
    proteinG: 17,
    carbsG: 28,
    fatG: 6,
  },
  {
    id: "starbucks-spinach-feta",
    chainId: "starbucks",
    name: "Spinach, Feta & Egg White Wrap",
    servingDescription: "1 wrap",
    calories: 290,
    proteinG: 20,
    carbsG: 33,
    fatG: 8,
  },
  {
    id: "starbucks-oatmeal",
    chainId: "starbucks",
    name: "Classic Whole Grain Oatmeal",
    servingDescription: "1 bowl · with nuts & dried fruit",
    calories: 320,
    proteinG: 10,
    carbsG: 52,
    fatG: 9,
  },
  {
    id: "starbucks-grande-latte",
    chainId: "starbucks",
    name: "Grande Caffè Latte · 2% milk",
    servingDescription: "16 fl oz",
    calories: 190,
    proteinG: 13,
    carbsG: 18,
    fatG: 7,
  },
  {
    id: "starbucks-grande-cold-brew",
    chainId: "starbucks",
    name: "Grande Cold Brew · black",
    servingDescription: "16 fl oz",
    calories: 5,
    proteinG: 0,
    carbsG: 0,
    fatG: 0,
  },
  {
    id: "starbucks-chicken-artisan",
    chainId: "starbucks",
    name: "Chicken & Bacon on Brioche",
    servingDescription: "1 sandwich",
    calories: 470,
    proteinG: 28,
    carbsG: 38,
    fatG: 22,
  },
  // Panera
  {
    id: "panera-chicken-salad",
    chainId: "panera",
    name: "Green Goddess Cobb Salad w/ Chicken",
    servingDescription: "1 whole salad",
    calories: 550,
    proteinG: 42,
    carbsG: 18,
    fatG: 35,
  },
  {
    id: "panera-greek-salad",
    chainId: "panera",
    name: "Greek Salad w/ Chicken",
    servingDescription: "1 whole salad",
    calories: 420,
    proteinG: 38,
    carbsG: 14,
    fatG: 22,
  },
  {
    id: "panera-ten-veg-soup",
    chainId: "panera",
    name: "Ten Vegetable Soup · bowl",
    servingDescription: "1 bread bowl excluded",
    calories: 100,
    proteinG: 3,
    carbsG: 16,
    fatG: 2,
  },
  {
    id: "panera-broccoli-cheddar",
    chainId: "panera",
    name: "Broccoli Cheddar Soup · bowl",
    servingDescription: "1 bowl",
    calories: 360,
    proteinG: 14,
    carbsG: 24,
    fatG: 24,
  },
  {
    id: "panera-turkey-avocado",
    chainId: "panera",
    name: "Turkey & Avocado BLT",
    servingDescription: "1 sandwich · whole",
    calories: 620,
    proteinG: 36,
    carbsG: 54,
    fatG: 28,
  },
  {
    id: "panera-chipotle-chicken",
    chainId: "panera",
    name: "Chipotle Chicken Avocado Melt",
    servingDescription: "1 sandwich · whole",
    calories: 640,
    proteinG: 42,
    carbsG: 56,
    fatG: 26,
  },
  {
    id: "panera-mediterranean-bowl",
    chainId: "panera",
    name: "Mediterranean Bowl w/ Chicken",
    servingDescription: "1 warm bowl",
    calories: 520,
    proteinG: 40,
    carbsG: 48,
    fatG: 18,
  },
  {
    id: "panera-plain-bagel",
    chainId: "panera",
    name: "Plain Bagel",
    servingDescription: "1 bagel",
    calories: 290,
    proteinG: 10,
    carbsG: 56,
    fatG: 2,
  },
  // Sweetgreen
  {
    id: "sweetgreen-harvest",
    chainId: "sweetgreen",
    name: "Harvest Bowl",
    servingDescription: "1 bowl",
    calories: 565,
    proteinG: 20,
    carbsG: 58,
    fatG: 28,
  },
  {
    id: "sweetgreen-chicken-pesto",
    chainId: "sweetgreen",
    name: "Chicken Pesto Parm Bowl",
    servingDescription: "1 bowl",
    calories: 520,
    proteinG: 38,
    carbsG: 32,
    fatG: 28,
  },
  {
    id: "sweetgreen-kale-caesar",
    chainId: "sweetgreen",
    name: "Kale Caesar w/ Chicken",
    servingDescription: "1 salad",
    calories: 480,
    proteinG: 36,
    carbsG: 18,
    fatG: 30,
  },
  {
    id: "sweetgreen-fish-taco",
    chainId: "sweetgreen",
    name: "Fish Taco Bowl",
    servingDescription: "1 bowl",
    calories: 540,
    proteinG: 32,
    carbsG: 48,
    fatG: 24,
  },
  {
    id: "sweetgreen-shroomami",
    chainId: "sweetgreen",
    name: "Shroomami",
    servingDescription: "1 bowl · warm",
    calories: 610,
    proteinG: 18,
    carbsG: 52,
    fatG: 38,
  },
  {
    id: "sweetgreen-guacamole-greens",
    chainId: "sweetgreen",
    name: "Guacamole Greens",
    servingDescription: "1 salad",
    calories: 430,
    proteinG: 24,
    carbsG: 28,
    fatG: 26,
  },
  // Cava
  {
    id: "cava-grains-greens",
    chainId: "cava",
    name: "Grains + Greens w/ Chicken",
    servingDescription: "1 bowl · typical build",
    calories: 610,
    proteinG: 42,
    carbsG: 52,
    fatG: 24,
  },
  {
    id: "cava-harissa-honey",
    chainId: "cava",
    name: "Harissa Honey Chicken Bowl",
    servingDescription: "1 bowl",
    calories: 640,
    proteinG: 44,
    carbsG: 54,
    fatG: 26,
  },
  {
    id: "cava-greens-bowl",
    chainId: "cava",
    name: "Greens + Grains w/ Lamb",
    servingDescription: "1 bowl",
    calories: 680,
    proteinG: 38,
    carbsG: 48,
    fatG: 36,
  },
  {
    id: "cava-spicy-lamb",
    chainId: "cava",
    name: "Spicy Lamb Meatballs Bowl",
    servingDescription: "1 bowl",
    calories: 720,
    proteinG: 36,
    carbsG: 56,
    fatG: 38,
  },
  {
    id: "cava-chicken-pita",
    chainId: "cava",
    name: "Grilled Chicken Pita",
    servingDescription: "1 pita",
    calories: 520,
    proteinG: 38,
    carbsG: 48,
    fatG: 18,
  },
  {
    id: "cava-super-greens",
    chainId: "cava",
    name: "Super Greens w/ Falafel",
    servingDescription: "1 salad bowl",
    calories: 480,
    proteinG: 16,
    carbsG: 44,
    fatG: 28,
  },
  // Shake Shack
  {
    id: "shakeshack-shackburger",
    chainId: "shakeshack",
    name: "ShackBurger",
    servingDescription: "1 burger",
    calories: 530,
    proteinG: 28,
    carbsG: 27,
    fatG: 34,
  },
  {
    id: "shakeshack-shack-stack",
    chainId: "shakeshack",
    name: "Shack Stack",
    servingDescription: "1 burger · cheeseburger + mushroom",
    calories: 770,
    proteinG: 38,
    carbsG: 42,
    fatG: 48,
  },
  {
    id: "shakeshack-chicken-shack",
    chainId: "shakeshack",
    name: "Chicken Shack",
    servingDescription: "1 sandwich",
    calories: 550,
    proteinG: 32,
    carbsG: 38,
    fatG: 30,
  },
  {
    id: "shakeshack-smoke-shack",
    chainId: "shakeshack",
    name: "SmokeShack",
    servingDescription: "1 burger · bacon & cherry peppers",
    calories: 610,
    proteinG: 32,
    carbsG: 28,
    fatG: 42,
  },
  {
    id: "shakeshack-crinkle-fries",
    chainId: "shakeshack",
    name: "Crinkle Cut Fries",
    servingDescription: "1 regular order",
    calories: 470,
    proteinG: 6,
    carbsG: 58,
    fatG: 24,
  },
  {
    id: "shakeshack-chicken-bites",
    chainId: "shakeshack",
    name: "Chicken Bites · 6 pc",
    servingDescription: "6 pieces",
    calories: 360,
    proteinG: 28,
    carbsG: 18,
    fatG: 20,
  },
  // Panda Express
  {
    id: "panda-orange-chicken",
    chainId: "panda",
    name: "Orange Chicken",
    servingDescription: "1 entree portion",
    calories: 490,
    proteinG: 25,
    carbsG: 51,
    fatG: 23,
  },
  {
    id: "panda-beijing-beef",
    chainId: "panda",
    name: "Beijing Beef",
    servingDescription: "1 entree portion",
    calories: 470,
    proteinG: 14,
    carbsG: 46,
    fatG: 26,
  },
  {
    id: "panda-kung-pao",
    chainId: "panda",
    name: "Kung Pao Chicken",
    servingDescription: "1 entree portion",
    calories: 290,
    proteinG: 20,
    carbsG: 18,
    fatG: 16,
  },
  {
    id: "panda-grilled-teriyaki",
    chainId: "panda",
    name: "Grilled Teriyaki Chicken",
    servingDescription: "1 entree portion",
    calories: 275,
    proteinG: 36,
    carbsG: 14,
    fatG: 8,
  },
  {
    id: "panda-broccoli-beef",
    chainId: "panda",
    name: "Broccoli Beef",
    servingDescription: "1 entree portion",
    calories: 150,
    proteinG: 9,
    carbsG: 13,
    fatG: 7,
  },
  {
    id: "panda-chow-mein",
    chainId: "panda",
    name: "Chow Mein",
    servingDescription: "1 side portion",
    calories: 510,
    proteinG: 13,
    carbsG: 61,
    fatG: 24,
  },
  {
    id: "panda-fried-rice",
    chainId: "panda",
    name: "Fried Rice",
    servingDescription: "1 side portion",
    calories: 520,
    proteinG: 11,
    carbsG: 78,
    fatG: 16,
  },
  {
    id: "panda-super-greens",
    chainId: "panda",
    name: "Super Greens",
    servingDescription: "1 side portion",
    calories: 90,
    proteinG: 6,
    carbsG: 10,
    fatG: 3,
  },
  // Popeyes
  {
    id: "popeyes-3-piece",
    chainId: "popeyes",
    name: "3 pc Tenders",
    servingDescription: "3 tenders",
    calories: 380,
    proteinG: 35,
    carbsG: 18,
    fatG: 18,
  },
  {
    id: "popeyes-5-piece",
    chainId: "popeyes",
    name: "5 pc Tenders",
    servingDescription: "5 tenders",
    calories: 630,
    proteinG: 58,
    carbsG: 30,
    fatG: 30,
  },
  {
    id: "popeyes-chicken-sandwich",
    chainId: "popeyes",
    name: "Chicken Sandwich",
    servingDescription: "1 sandwich · classic",
    calories: 700,
    proteinG: 28,
    carbsG: 50,
    fatG: 42,
  },
  {
    id: "popeyes-spicy-sandwich",
    chainId: "popeyes",
    name: "Spicy Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 720,
    proteinG: 28,
    carbsG: 52,
    fatG: 44,
  },
  {
    id: "popeyes-2-piece",
    chainId: "popeyes",
    name: "2 pc Chicken · mixed",
    servingDescription: "2 pieces · leg & thigh",
    calories: 420,
    proteinG: 28,
    carbsG: 14,
    fatG: 28,
  },
  {
    id: "popeyes-red-beans-rice",
    chainId: "popeyes",
    name: "Red Beans & Rice · regular",
    servingDescription: "1 regular side",
    calories: 230,
    proteinG: 8,
    carbsG: 24,
    fatG: 11,
  },
  {
    id: "popeyes-cajun-fries",
    chainId: "popeyes",
    name: "Cajun Fries · regular",
    servingDescription: "1 regular order",
    calories: 260,
    proteinG: 4,
    carbsG: 34,
    fatG: 12,
  },
  // Five Guys
  {
    id: "fiveguys-little-burger",
    chainId: "fiveguys",
    name: "Little Hamburger",
    servingDescription: "1 burger",
    calories: 480,
    proteinG: 23,
    carbsG: 39,
    fatG: 26,
  },
  {
    id: "fiveguys-hamburger",
    chainId: "fiveguys",
    name: "Hamburger",
    servingDescription: "1 burger · 2 patties",
    calories: 700,
    proteinG: 39,
    carbsG: 39,
    fatG: 43,
  },
  {
    id: "fiveguys-bacon-burger",
    chainId: "fiveguys",
    name: "Bacon Burger",
    servingDescription: "1 burger · 2 patties + bacon",
    calories: 780,
    proteinG: 43,
    carbsG: 40,
    fatG: 50,
  },
  {
    id: "fiveguys-little-cheese",
    chainId: "fiveguys",
    name: "Little Cheeseburger",
    servingDescription: "1 burger · 1 patty + cheese",
    calories: 550,
    proteinG: 27,
    carbsG: 40,
    fatG: 32,
  },
  {
    id: "fiveguys-grilled-cheese",
    chainId: "fiveguys",
    name: "Grilled Cheese",
    servingDescription: "1 sandwich",
    calories: 430,
    proteinG: 16,
    carbsG: 42,
    fatG: 22,
  },
  {
    id: "fiveguys-fries-regular",
    chainId: "fiveguys",
    name: "Regular Fries",
    servingDescription: "1 regular order",
    calories: 620,
    proteinG: 8,
    carbsG: 78,
    fatG: 30,
  },
  {
    id: "fiveguys-hot-dog",
    chainId: "fiveguys",
    name: "Hot Dog",
    servingDescription: "1 hot dog · with bun",
    calories: 520,
    proteinG: 18,
    carbsG: 40,
    fatG: 32,
  },
  // In-N-Out
  {
    id: "innout-double-double",
    chainId: "in-n-out",
    name: "Double-Double",
    servingDescription: "1 burger",
    calories: 670,
    proteinG: 37,
    carbsG: 39,
    fatG: 41,
  },
  {
    id: "innout-hamburger",
    chainId: "in-n-out",
    name: "Hamburger",
    servingDescription: "1 burger",
    calories: 390,
    proteinG: 16,
    carbsG: 39,
    fatG: 19,
  },
  {
    id: "innout-cheeseburger",
    chainId: "in-n-out",
    name: "Cheeseburger",
    servingDescription: "1 burger",
    calories: 480,
    proteinG: 22,
    carbsG: 39,
    fatG: 27,
  },
  {
    id: "innout-protein-style",
    chainId: "in-n-out",
    name: "Double-Double Protein Style",
    servingDescription: "1 burger · lettuce wrap",
    calories: 520,
    proteinG: 33,
    carbsG: 11,
    fatG: 39,
  },
  {
    id: "innout-grilled-cheese",
    chainId: "in-n-out",
    name: "Grilled Cheese",
    servingDescription: "1 sandwich",
    calories: 380,
    proteinG: 14,
    carbsG: 42,
    fatG: 18,
  },
  {
    id: "innout-fries",
    chainId: "in-n-out",
    name: "French Fries",
    servingDescription: "1 regular order",
    calories: 395,
    proteinG: 7,
    carbsG: 54,
    fatG: 18,
  },
  {
    id: "innout-neapolitan-shake",
    chainId: "in-n-out",
    name: "Neapolitan Shake",
    servingDescription: "1 shake · 15 oz",
    calories: 580,
    proteinG: 15,
    carbsG: 74,
    fatG: 26,
  },
  // Culver's
  {
    id: "culvers-butterburger-single",
    chainId: "culvers",
    name: "ButterBurger Single",
    servingDescription: "1 burger",
    calories: 390,
    proteinG: 20,
    carbsG: 39,
    fatG: 19,
  },
  {
    id: "culvers-butterburger-double",
    chainId: "culvers",
    name: "ButterBurger Double",
    servingDescription: "1 burger · 2 patties",
    calories: 560,
    proteinG: 34,
    carbsG: 39,
    fatG: 32,
  },
  {
    id: "culvers-butterburger-cheese-single",
    chainId: "culvers",
    name: "ButterBurger Cheese, Single",
    servingDescription: "1 burger",
    calories: 460,
    proteinG: 23,
    carbsG: 40,
    fatG: 25,
  },
  {
    id: "culvers-butterburger-cheese-double",
    chainId: "culvers",
    name: "ButterBurger Cheese, Double",
    servingDescription: "1 burger · 2 patties",
    calories: 700,
    proteinG: 40,
    carbsG: 41,
    fatG: 44,
  },
  {
    id: "culvers-deluxe-single",
    chainId: "culvers",
    name: "The Culver's Deluxe, Single",
    servingDescription: "1 burger · lettuce, tomato, pickle, onion",
    calories: 570,
    proteinG: 23,
    carbsG: 42,
    fatG: 36,
  },
  {
    id: "culvers-bacon-deluxe-single",
    chainId: "culvers",
    name: "The Culver's Bacon Deluxe, Single",
    servingDescription: "1 burger · bacon, lettuce, tomato",
    calories: 610,
    proteinG: 27,
    carbsG: 42,
    fatG: 39,
  },
  {
    id: "culvers-mushroom-swiss-single",
    chainId: "culvers",
    name: "Mushroom & Swiss, Single",
    servingDescription: "1 burger",
    calories: 490,
    proteinG: 26,
    carbsG: 40,
    fatG: 27,
  },
  {
    id: "culvers-curderburger",
    chainId: "culvers",
    name: "Culver's CurderBurger",
    servingDescription: "1 burger · cheese curd on top",
    calories: 510,
    proteinG: 20,
    carbsG: 40,
    fatG: 28,
  },
  {
    id: "culvers-crispy-chicken-sandwich",
    chainId: "culvers",
    name: "Crispy Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 460,
    proteinG: 25,
    carbsG: 57,
    fatG: 16,
  },
  {
    id: "culvers-grilled-chicken-sandwich",
    chainId: "culvers",
    name: "Grilled Chicken Sandwich",
    servingDescription: "1 sandwich",
    calories: 390,
    proteinG: 41,
    carbsG: 39,
    fatG: 8,
  },
  {
    id: "culvers-chicken-tenders-4",
    chainId: "culvers",
    name: "Original Chicken Tenders",
    servingDescription: "4 pieces",
    calories: 540,
    proteinG: 40,
    carbsG: 42,
    fatG: 24,
  },
  {
    id: "culvers-buffalo-tenders-4",
    chainId: "culvers",
    name: "Buffalo Chicken Tenders",
    servingDescription: "4 pieces",
    calories: 460,
    proteinG: 35,
    carbsG: 32,
    fatG: 21,
  },
  {
    id: "culvers-cod-sandwich",
    chainId: "culvers",
    name: "North Atlantic Cod Filet Sandwich",
    servingDescription: "1 sandwich",
    calories: 600,
    proteinG: 27,
    carbsG: 48,
    fatG: 34,
  },
  {
    id: "culvers-fries-regular",
    chainId: "culvers",
    name: "Crinkle Cut Fries",
    servingDescription: "1 regular order",
    calories: 360,
    proteinG: 6,
    carbsG: 53,
    fatG: 14,
  },
  {
    id: "culvers-fries-large",
    chainId: "culvers",
    name: "Crinkle Cut Fries, Large",
    servingDescription: "1 large order",
    calories: 460,
    proteinG: 7,
    carbsG: 68,
    fatG: 18,
  },
  {
    id: "culvers-cheese-curds-medium",
    chainId: "culvers",
    name: "Wisconsin Cheese Curds",
    servingDescription: "1 medium order",
    calories: 490,
    proteinG: 17,
    carbsG: 46,
    fatG: 27,
  },
  {
    id: "culvers-cheese-curds-large",
    chainId: "culvers",
    name: "Wisconsin Cheese Curds, Large",
    servingDescription: "1 large order",
    calories: 980,
    proteinG: 34,
    carbsG: 91,
    fatG: 54,
  },
  {
    id: "culvers-chili-cheddar-fries",
    chainId: "culvers",
    name: "Chili Cheddar Fries",
    servingDescription: "1 order",
    calories: 670,
    proteinG: 20,
    carbsG: 77,
    fatG: 31,
  },
  {
    id: "culvers-onion-rings-medium",
    chainId: "culvers",
    name: "Onion Rings",
    servingDescription: "1 medium order",
    calories: 400,
    proteinG: 6,
    carbsG: 44,
    fatG: 22,
  },
  {
    id: "culvers-coleslaw",
    chainId: "culvers",
    name: "Coleslaw",
    servingDescription: "1 side",
    calories: 210,
    proteinG: 0,
    carbsG: 15,
    fatG: 17,
  },
  {
    id: "culvers-georges-chili",
    chainId: "culvers",
    name: "George's Chili",
    servingDescription: "1 medium bowl",
    calories: 310,
    proteinG: 18,
    carbsG: 31,
    fatG: 13,
  },
  {
    id: "culvers-garden-fresco-chicken",
    chainId: "culvers",
    name: "Garden Fresco Salad w/ Grilled Chicken",
    servingDescription: "1 salad",
    calories: 330,
    proteinG: 39,
    carbsG: 19,
    fatG: 12,
  },
  {
    id: "culvers-oreo-concrete-short",
    chainId: "culvers",
    name: "Oreo Concrete Mixer",
    servingDescription: "1 short · frozen custard",
    calories: 680,
    proteinG: 13,
    carbsG: 88,
    fatG: 34,
  },
  {
    id: "culvers-chocolate-shake-medium",
    chainId: "culvers",
    name: "Chocolate Shake",
    servingDescription: "1 medium · 16 fl oz",
    calories: 800,
    proteinG: 12,
    carbsG: 106,
    fatG: 37,
  },
] as const;

const chainById = new Map(RESTAURANT_CHAINS.map((chain) => [chain.id, chain]));

export function getRestaurantChain(chainId: string): RestaurantChain | undefined {
  return chainById.get(chainId);
}

export interface RestaurantSearchHit {
  chain: RestaurantChain;
  item: RestaurantMenuItem;
}

export function searchRestaurantMenu(query: string, limit = 40): RestaurantSearchHit[] {
  const normalized = query.trim().toLowerCase();
  if (normalized.length < 2) return [];

  const normalizedChainKey = normalized.replace(/[^a-z0-9]/g, "");
  const matchingChains = RESTAURANT_CHAINS.filter(
    (chain) =>
      chain.name.toLowerCase().includes(normalized) ||
      chain.id.includes(normalizedChainKey) ||
      normalizedChainKey.includes(chain.id)
  );

  const hits: RestaurantSearchHit[] = [];
  const seen = new Set<string>();

  function pushItem(item: RestaurantMenuItem) {
    if (seen.has(item.id) || hits.length >= limit) return;
    const chain = chainById.get(item.chainId);
    if (!chain) return;
    seen.add(item.id);
    hits.push({ chain, item });
  }

  if (matchingChains.length > 0) {
    for (const chain of matchingChains) {
      for (const item of RESTAURANT_MENU_ITEMS) {
        if (item.chainId === chain.id) pushItem(item);
      }
    }
    if (hits.length >= limit) return hits;
  }

  for (const item of RESTAURANT_MENU_ITEMS) {
    const chain = chainById.get(item.chainId);
    if (!chain) continue;

    const haystack =
      `${chain.name} ${item.name} ${item.servingDescription}`.toLowerCase();
    if (!haystack.includes(normalized)) continue;

    pushItem(item);
  }

  return hits;
}

export function listRestaurantChains(): RestaurantChain[] {
  return [...RESTAURANT_CHAINS];
}
